source 'https://rubygems.org'

gem 'jekyll', '2.4.0'
gem 'jekyll-assets'
gem 'jekyll-paginate'
gem 'kramdown'
gem 'rake'
gem 'sass'
gem 'uglifier'
gem 'github-pages'

# gem 'jekyll-picture-tag', :git => 'https://github.com/websiddu/jekyll-picture-tag.git'
gem 'mini_magick'
gem 'fastimage'
gem 'redcarpet'
